language: generic

sudo: required

services:
  - docker

before_script:
  - cd docker && docker-compose build

script:
  - docker-compose run -e KEY=$COVERALLS_REPO_TOKEN --rm web bash docker/run_unittests.sh
