# main container that runs the web interface on host port 8642
web:
  build: ./webapp
  ports:
    - "8643:8080"
  volumes:
    - ..:/code/SM_distributed
    - ../test/data/:/data # mount directory with datasets to /data
  links:
    - postgres # must be the host name in the config
  working_dir: /code/SM_distributed
  restart: always
  # wait a few seconds for postgres to initialize and start web interface
  command: bash -c 'sleep 10 && source activate sm_distributed && PYTHONPATH=. python webapp/webserver.py --config /code/SM_distributed/docker/config.json'

# data-only container for storing the database
dbdata:
  image: postgres:latest
  entrypoint: /bin/true
  volumes:
    - /var/lib/postgresql

# container that runs the database
postgres:
  build: ./database
  volumes_from:
    - dbdata
  restart: always
